#!/usr/bin/env python3
"""
Voice Notes System Configuration Setup Script

This script helps users set up their API keys and configuration securely.
"""

import os
import sys
from pathlib import Path
from getpass import getpass


def setup_environment_file():
    """Create and populate the .env file with user's API keys."""
    env_file = Path(".env")
    env_template = Path(".env.template")

    print("=== Voice Notes System Configuration Setup ===\n")

    # Check if .env already exists
    if env_file.exists():
        overwrite = input(f"{env_file} already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return False

    # Read template
    if not env_template.exists():
        print(f"Error: {env_template} not found!")
        return False

    with open(env_template, 'r') as f:
        template_content = f.read()

    print("Please provide your API keys and configuration:")
    print("(Press Enter to skip optional fields)\n")

    # Get OpenAI API key
    openai_key = getpass("OpenAI API Key (required): ").strip()
    if not openai_key:
        print("Error: OpenAI API key is required!")
        return False

    # Get MCP server details
    print("\nMCP (Model Context Protocol) Server Configuration:")
    mcp_url = input("MCP Server URL (optional): ").strip()
    mcp_key = getpass("MCP API Key (optional): ").strip() if mcp_url else ""

    # Get optional paths
    print("\nOptional Custom Paths:")
    output_dir = input("Voice Notes Output Directory (optional): ").strip()
    config_dir = input("Configuration Directory (optional): ").strip()

    # Get logging level
    print("\nLogging Configuration:")
    log_levels = ["DEBUG", "INFO", "WARNING", "ERROR"]
    print(f"Available log levels: {', '.join(log_levels)}")
    log_level = input("Log Level (optional, default: INFO): ").strip().upper()
    if log_level and log_level not in log_levels:
        print(f"Warning: '{log_level}' is not a standard log level")

    # Create .env content
    env_content = f"""# Voice Notes System Environment Variables
# Generated by setup script

# OpenAI API Configuration
OPENAI_API_KEY={openai_key}

# MCP Server Configuration
MCP_SERVER_URL={mcp_url}
MCP_API_KEY={mcp_key}

# Optional: Custom paths
VOICE_NOTES_OUTPUT_DIR={output_dir}
VOICE_NOTES_CONFIG_DIR={config_dir}

# Optional: Logging level override
LOG_LEVEL={log_level or 'INFO'}
"""

    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print(f"\n✅ Configuration saved to {env_file}")

        # Set secure permissions (readable by owner only)
        os.chmod(env_file, 0o600)
        print("✅ File permissions set to owner-only read/write")

        return True

    except Exception as e:
        print(f"Error writing {env_file}: {e}")
        return False


def validate_configuration():
    """Validate the configuration and test API connections."""
    print("\n=== Validating Configuration ===")

    try:
        # Add src directory to path so we can import our modules
        sys.path.insert(0, str(Path(__file__).parent / "src"))
        from config_manager import ConfigManager

        config = ConfigManager()
        validation_results = config.validate_configuration()

        print("\nConfiguration Validation Results:")
        for item, is_valid in validation_results.items():
            status = "✅" if is_valid else "❌"
            print(f"{status} {item}: {'Valid' if is_valid else 'Invalid/Missing'}")

        # Test OpenAI API connection
        if validation_results.get('openai_api_key'):
            print("\n=== Testing API Connections ===")
            test_openai_connection(config)

        return all(validation_results.values())

    except ImportError as e:
        print(f"Error importing configuration manager: {e}")
        return False
    except Exception as e:
        print(f"Error validating configuration: {e}")
        return False


def test_openai_connection(config):
    """Test OpenAI API connection."""
    try:
        import openai

        openai_config = config.get_openai_config()
        client = openai.OpenAI(api_key=openai_config['api_key'])

        # Test with a simple API call
        print("Testing OpenAI API connection...")

        # List available models (lightweight test)
        models = client.models.list()
        print("✅ OpenAI API connection successful")

        # Check if Whisper model is available
        whisper_available = any(model.id == "whisper-1" for model in models.data)
        if whisper_available:
            print("✅ Whisper-1 model is available")
        else:
            print("⚠️  Whisper-1 model not found in available models")

    except Exception as e:
        print(f"❌ OpenAI API connection failed: {e}")


def setup_output_directory():
    """Create the output directory for voice notes."""
    try:
        sys.path.insert(0, str(Path(__file__).parent / "src"))
        from config_manager import ConfigManager

        config = ConfigManager()
        files_config = config.get_files_config()
        output_dir = Path(files_config.get('output_directory', '~/Documents/Voice Notes'))

        # Expand user directory
        output_dir = output_dir.expanduser()

        # Create directory
        output_dir.mkdir(parents=True, exist_ok=True)
        print(f"✅ Output directory created: {output_dir}")

        return True

    except Exception as e:
        print(f"❌ Error creating output directory: {e}")
        return False


def main():
    """Main setup function."""
    print("Voice Notes System - Configuration Setup")
    print("=" * 50)

    # Step 1: Set up environment file
    if not setup_environment_file():
        print("❌ Setup failed!")
        return 1

    # Step 2: Set up output directory
    setup_output_directory()

    # Step 3: Validate configuration
    if validate_configuration():
        print("\n🎉 Setup completed successfully!")
        print("\nNext steps:")
        print("1. Review config/config.yaml for additional settings")
        print("2. Run the voice notes system")
        print("3. Test recording with your configured hotkeys")
        return 0
    else:
        print("\n⚠️  Setup completed with warnings.")
        print("Please review the validation results above and fix any issues.")
        return 1


if __name__ == "__main__":
    sys.exit(main())